/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */
#include <stdint.h>
#include <stdio.h>
//#include "system_stm32f4xx.h"
#include "systic.h"
#include "led.h"

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif


int main(void)
{
	SystemInit();
	led_init(LED_BLUE_PIN);
	SysTick_Config(SystemCoreClock/1000);
	while(1)
	{
		led_on(LED_BLUE_PIN);
		SysTick_Delay(5000);
		led_off(LED_BLUE_PIN);
		SysTick_Delay(5000);
	}
	return 0;
}













