/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */
#include <stdint.h>
#include <stdio.h>
#include "stm32f4xx.h"
#include "system_stm32f4xx.h"
#include "led.h"
#include "uart.h"

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

int main(void)
{
	SystemInit();

	//printf("Hello stm 32\n");

   led_init(LED_BLUE_PIN);
   led_init(LED_RED_PIN);
   init_uart(9600);
   int choice;
   uartputs("1. Red Led On\r\n2. Red Led Off\r\n3. Blue Led On\r\n4. Blue Led Off\r\n");
   char ch[2];
   while(1)
   {
	   uartgets(ch);
	   sscanf(ch, "%d", &choice);
	   switch(choice)
	   {
	   case 1: led_on(LED_RED_PIN);
	   	   	   break;

	   case 2: led_off(LED_RED_PIN);
	   	   	   	break;

	   case 3: led_on(LED_BLUE_PIN);
	   	   	   	break;

	   case 4: led_off(LED_BLUE_PIN);
	   	   	   	 break;
	   default: uartputs("Invalid choice\r\n");
	   }


   }

	return 0;
}













