/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdio.h>
#include "stm32f4xx.h"
#include "system_stm32f4xx.h"

#include "accel.h"
#include "i2c_lcd.h"

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

int main(void) {
	char str[100];
	LIS_Data val;
	SystemInit();
	LIS_Init(); //initialize accel
	Lcd_Init();
	while(1) {
		if(LIS_IsDataAvail()) // check if new data avail
		{
			val = LIS_GetData(); // get the new data
			// print value

			sprintf(str, "X: %d  Y: %d  Z: %d", val.x, val.y, val.z);
			for(int i=0; i<27; i++)
			{
			Lcd_WriteByte(LCD_CMD, LCD_DISP_SHIFT_LEFT);
			Lcd_Puts(LCD_LINE1, str);
			DelayMs(500);
			}

			//Lcd_Puts(LCD_LINE2, str);
			}
		Lcd_WriteByte(LCD_CMD, LCD_CLEAR);
		DelayMs(10);
	}
	return 0;
}
