/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdio.h>
#include "stm32f4xx.h"
#include "system_stm32f4xx.h"

#include "accel.h"
#include "led.h"

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

int main(void) {

	char str[32];
	LIS_Data val;
	SystemInit();
	led_init(LED_ORANGE_PIN);
	led_init(LED_GREEN_PIN);
	led_init(LED_BLUE_PIN);
	led_init(LED_RED_PIN);
	LIS_Init(); //initialize accel
	while(1) {
		if(LIS_IsDataAvail()) // check if new data avail
		{
			val = LIS_GetData(); // get the new data
			// print value
			sprintf(str, "X=%d, Y=%d, Z=%d\r\n", val.x, val.y, val.z);

			if(val.x > 3500) //POSTIVE X-direction
			{
				led_on(LED_RED_PIN);
				remaining_off(LED_ORANGE_PIN, LED_BLUE_PIN, LED_GREEN_PIN);
			}

			else if(val.x < -3500) //NEGATIVE X-direction
			{
				led_on(LED_GREEN_PIN);
				remaining_off(LED_ORANGE_PIN, LED_BLUE_PIN, LED_RED_PIN);
			}

			else if(val.y > 2500)//POSITIVE Y-DIRECTION
			{
				led_on(LED_ORANGE_PIN);
				remaining_off(LED_RED_PIN, LED_BLUE_PIN, LED_GREEN_PIN);

			}

			else if(val.y < -2500) //NEGATIVE Y-DIRECTION
			{
				led_on(LED_BLUE_PIN);
				remaining_off(LED_RED_PIN, LED_ORANGE_PIN, LED_GREEN_PIN);
			}

			else
			{
				led_off(LED_ORANGE_PIN);
				led_off(LED_GREEN_PIN);
				led_off(LED_RED_PIN);
				led_off(LED_BLUE_PIN);
			}

		}


}
	return 0;
}


